version: '3.4'

services: 
  web:
    image: nginx:1.14.2-alpine
    restart: always
    volumes:
      - ./public_html:/public_html
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/conf.d:/etc/nginx/
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - 80:80
      - 443:443
    
  # certbot:
  #    image: certbot/certbot:latest
  #    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email rltjr1092@gmail.com --agree-tos --no-eff-email -d www.boostcamp.shop:19785
  #    volumes:
  #      - ./certbot/conf2/:/etc/letsencrypt
  #      - ./certbot/logs2/:/var/log/letsencrypt
  #      - ./certbot/data2:/usr/share/nginx/html/letsencrypt