name: CLIENT CI

on:
  pull_request:
    branches: ['dev']
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  client_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
          
      - name: Setting .env.development
        run: |
          cd ./frontend
          echo "REACT_APP_GITHUB_OAUTH=${{ secrets.REACT_APP_GITHUB_OAUTH_DEV }}" >> .env.development
          echo "REACT_APP_NODE_ENV=${{ secrets.REACT_APP_NODE_ENV_DEV }}" >> .env.development
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL_DEV }}" >> .env.development
          echo "REACT_APP_SOCKET_URL=${{ secrets.REACT_APP_SOCKET_URL_DEV }}" >> .env.development
          echo "BROWSER=${{ secrets.BROWSER }}" >> .env.development
          cat .env.development

      - name: Install and Test
        run: |
          cd ./frontend
          npm ci
          npm run test
        env:
          CI: false
