name: CLIENT CI

on:
  pull_request:
    branches: ['dev']
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  client_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install and Test
        run: |
          cd ./frontend
          npm ci
          npm run test
        env:
          CI: false
