name: COMPILER CI

on:
  pull_request:
    branches: ['dev']
    paths:
      - 'backend/compiler/**'
  workflow_dispatch:

jobs:
  compiler_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/compiler/package-lock.json'

      - run: |
          cd ./backend/compiler
          npm ci
          npm test
