name: 'deploy when push'

on:
  push:
    branches: ['dev']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /root/codocs/ && git checkout dev && git pull
            cd /root/codocs/backend/api && npm ci
            cd /root/codocs/backend/socket && npm ci
            cd /root/codocs/backend/compiler && npm ci
            cd /root/codocs/frontend && npm ci
            cd /root/codocs/ && npm ci
            npm run start
